crm_project/crm/urls.py
from . import views
from django.urls import path

app_name = 'crm'

# all of the paths have crm/ before them. example crm/cars to show all the cars and their data 
urlpatterns = [ 
    # Define your app's URL patterns here
    path('dashboard/', views.dashboard, name='dashboard'),
    # customers
    path('customer/', views.customer_details, name='customer_details'),
    path('add_customer/', views.add_customer, name='add_customer'),
    path('update_customer/<int:user_id>/', views.update_customer, name="update_customer"),
    path('delete_customer/<int:user_id>/', views.delete_customer, name='delete_customer'),
    # cars get_car_options
    path('cars/', views.show_all_cars, name='show_all_cars'),
    path('add_car/', views.add_car, name='add_car'),
    path('get_car_details/', views.get_car_details, name='get_car_details'),
    path('update_car/<int:car_id>/', views.update_car, name='update_car'),
    path('delete_car/<int:car_id>/', views.delete_car, name='delete_car'),
    # sell
    path('transaction_list/', views.transaction_list, name='transaction_list'),
    path('add_transaction/', views.add_transaction, name='add_transaction'),
    path('update_transaction/<int:transaction_id>/', views.update_transaction, name='update_transaction'),
    path('delete_transaction/<int:transaction_id>/', views.delete_transaction, name='delete_transaction'),
    path('sold/', views.sold, name='sold'),
    # lease
    path('leasing_list/', views.leasing_list, name='leasing_list'),
    path('add_lease/', views.add_lease, name='add_lease'),
    path('update_lease/<int:lease_id>/', views.update_lease, name='update_lease'),
    path('delete_lease/<int:lease_id>/', views.delete_lease, name='delete_lease'),
    path('lease/', views.lease, name='lease'),
    
]

crm_project/crm_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('crm/', include('crm.urls',namespace='crm')),
    path('', include('home.urls',namespace='home')),
]

crm_project/crm/models.py
from django.db import models
from decimal import Decimal
from django.utils.crypto import get_random_string



class Cars(models.Model):
    brand = models.CharField(max_length=50,null=True)
    model = models.CharField(max_length=50,null=True)
    year = models.IntegerField(null=True)
    color = models.CharField(max_length=20,null=True)
    engine =  models.CharField(max_length=20,null=True)
    more_info = models.TextField(null=True)
    total_available_number = models.IntegerField(null=True)
    number_of_cars_in_lease = models.IntegerField(null=True)
    is_still_in_stock = models.BooleanField(null=True)

    def __str__(self):
        return f"{self.brand}"

    def is_still_in_stock_method(self):
        return self.total_available_number > 0


    def sold(self, number_of_sold):
        if self.total_available_number >= number_of_sold:
            self.total_available_number -= number_of_sold
            self.save()  # Save the updated value to the database
        else:
            # Handle the case where the available number is less than the sold quantity
            raise ValueError("Not enough cars available for sale.")

    def lease(self, number_of_lease):
        if self.total_available_number >= number_of_lease:
            self.total_available_number -= number_of_lease
            if self.number_of_cars_in_lease is not None:
                self.number_of_cars_in_lease += number_of_lease
            else:
                self.number_of_cars_in_lease = number_of_lease
            self.save()  # Save the updated value to the database
        else:
            # Handle the case where the available number is less than the leased quantity
            raise ValueError("Not enough cars available for lease.")


    def save(self, *args, **kwargs):
        # Calculate the is_still_in_stock only if it's not set or needs an update
        if self.is_still_in_stock is None or self.is_still_in_stock != self.is_still_in_stock_method():
            self.is_still_in_stock = self.is_still_in_stock_method()

        super().save(*args, **kwargs)




class Customer(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone_number = models.IntegerField()
    address = models.TextField()

    cars = models.ForeignKey('Cars', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f"{self.name}"



class Transaction(models.Model):
    customer = models.ForeignKey('Customer', on_delete=models.CASCADE)
    car = models.ForeignKey('Cars', on_delete=models.CASCADE,null=True, blank=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField()
    receipt = models.CharField(max_length=50, unique=True)  # Unique constraint for the receipt ID

    def generate_receipt_id(self):
        # Combines 'R-Nr-' with a random 6-digit number
        return f'R-Nr-{get_random_string(length=6, allowed_chars="1234567890")}'

    def save(self, *args, **kwargs):
        # Generate receipt ID 
        if not self.receipt:
            self.receipt = self.generate_receipt_id()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Transaction #{self.id} - Receipt: {self.receipt} - {self.customer.name} "



class Leasing(models.Model):
    customer = models.ForeignKey('Customer', on_delete=models.CASCADE)
    car = models.ForeignKey('Cars', on_delete=models.CASCADE,null=True, blank=True)
    lease_start_date = models.DateField()
    lease_end_date = models.DateField()
    amount = models.DecimalField(default=0.0,max_digits=10, decimal_places=2, null=True)
    mark_as_returned_from_lease = models.BooleanField(default=False, null=True, blank=True)

    def calculate_amount(self):
        # fixed cost per day, $20
        cost_per_day = Decimal('20')
        
        # Calculate the number of days between start and end dates
        num_days = (self.lease_end_date - self.lease_start_date).days + 1
        
        # Calculate the total amount
        total_amount = cost_per_day * num_days

        return total_amount

    def mark_car_as_returned(self):
        if self.mark_as_returned_from_lease:
            self.car.number_of_cars_in_lease -= 1
            self.car.total_available_number += 1
            self.car.save()

    def un_mark_car_as_returned(self):
        if not self.mark_as_returned_from_lease:
            self.car.number_of_cars_in_lease += 1
            self.car.total_available_number -= 1
            self.car.save()

    def save(self, *args, **kwargs):
        # Calculate the amount only if it's not set or needs an update
        if self.amount is None or self.amount != self.calculate_amount():
            self.amount = self.calculate_amount()

        # Check if mark_as_returned_from_lease has changed
        if self.pk is not None:
            orig = Leasing.objects.get(pk=self.pk)
            if orig.mark_as_returned_from_lease != self.mark_as_returned_from_lease:
                if self.mark_as_returned_from_lease:
                    self.mark_car_as_returned()
                else:
                    self.un_mark_car_as_returned()

        super().save(*args, **kwargs)

    def __str__(self):
        return f"Leasing #{self.id} - {self.customer.name} - {self.car.brand} - Amount: ${self.amount}"







crm_project/crm/forms.py
from django import forms
from .models import Cars,Customer,Transaction,Leasing

class CarForm(forms.ModelForm):
    class Meta:
        model = Cars
        fields = ['brand','model','year', 'color','engine', 'more_info', 'total_available_number']


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['name', 'email', 'phone_number','address']



class TransactionForm(forms.ModelForm):
    number_of_cars = forms.IntegerField(label='Number of Cars')

    class Meta:
        model = Transaction
        fields = ['customer', 'car', 'amount', 'date', 'number_of_cars']


class UpdateTransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['customer', 'car', 'amount', 'date']



class LeasingForm(forms.ModelForm):
    number_of_cars = forms.IntegerField(label='Number of Cars')
    class Meta:
        model = Leasing
        fields = ['customer', 'car', 'lease_start_date', 'lease_end_date','number_of_cars']


class UpdateLeasingForm(forms.ModelForm):
    class Meta:
        model = Leasing
        fields = ['customer', 'car', 'lease_start_date', 'lease_end_date','amount','mark_as_returned_from_lease']

crm_project/crm/views.py
# crm_app/views.py
from django.shortcuts import render, get_object_or_404,redirect
from .forms import CarForm,CustomerForm,TransactionForm,UpdateTransactionForm,LeasingForm,UpdateLeasingForm
from django.http import JsonResponse
from .models import Cars,Customer,Transaction,Leasing
from django.contrib.auth.decorators import login_required



@login_required
def dashboard(request):
    return render(request, 'crm/dashboard.html')



# customers view
@login_required
def customer_details(request):
    customers = Customer.objects.all()
    context = {'customers': customers}

    return render(request, 'crm/customer/customer_details.html', context)



@login_required
def add_customer(request):
    if request.method == "POST":
        form = CustomerForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('crm:customer_details')
    else:
        form = CustomerForm()

    return render(request, 'crm/customer/add_customer.html', {'form': form})


def update_customer(request, user_id):
    customer = get_object_or_404(Customer, id=user_id)

    if request.method == 'POST':
        form = CustomerForm(request.POST, instance=customer)
        if form.is_valid():
            form.save()
            return redirect('crm:customer_details')
    else:
        form = CustomerForm(instance=customer)

    return render(request, 'crm/customer/customer_update_form.html', {'form': form, 'customer': customer})




def delete_customer(request, user_id):
    customer = get_object_or_404(Customer, id=user_id)

    if request.method == 'DELETE':
        customer.delete()
        return JsonResponse({'message': 'Customer deleted successfully'}, status=200)
    
    return JsonResponse({'error': 'Invalid request method'}, status=400)


# cars view  
def get_car_details(request):
    if request.method == 'GET':
        car_id = request.GET.get('id')
        try:
            car = Cars.objects.get(id=car_id)
            car_details = {
                'model': car.model,
                'year': car.year,
                'color': car.color,
                'engine': car.engine,
                'total_available_number': car.total_available_number,
                'is_still_in_stock': car.is_still_in_stock
            }
            return JsonResponse(car_details)
        except Cars.DoesNotExist:
            return JsonResponse({'error': 'Car not found.'}, status=404)

    return JsonResponse({'error': 'Invalid request method.'}, status=400)




@login_required
def show_all_cars(request):
    cars = Cars.objects.all()
    context = {'cars': cars}
    return render(request, 'crm/cars/cars_dashboard.html', context)

@login_required
def add_car(request):
    if request.method == 'POST':
        form = CarForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('crm:show_all_cars')
    else:
        form = CarForm()

    return render(request, 'crm/cars/add_car.html', {'form': form})

@login_required
def update_car(request, car_id):
    car = get_object_or_404(Cars, id=car_id)

    if request.method == 'POST':
        form = CarForm(request.POST, instance=car)
        if form.is_valid():
            form.save()
            return redirect('crm:show_all_cars')
    else:
        form = CarForm(instance=car)

    return render(request, 'crm/cars/car_update_form.html', {'form': form, 'car': car})


# @login_required(login_url='/') #redirect when user is not logged in
@login_required
def delete_car(request, car_id):
    car = get_object_or_404(Cars, id=car_id)

    if request.method == 'DELETE':
        car.delete()
        return JsonResponse({'message': 'Car deleted successfully'}, status=200)
    
    return JsonResponse({'error': 'Invalid request method'}, status=400)



# transactions view

@login_required
def transaction_list(request):
    transactions = Transaction.objects.all()
    context = {'transactions': transactions}
    return render(request, 'crm/sell/transaction_list.html', context)


@login_required
def add_transaction(request):
    if request.method == 'POST':
        form = TransactionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('crm:transaction_list')
        else:
            # Form is not valid, handle the errors
            print("Form errors:", form.errors)
    else:
        form = TransactionForm()

    return render(request, 'crm/sell/sell_a_car.html', {'transaction_form': form})


def sold(request):
    if request.method == 'POST':
        car_id = request.POST.get('id')
        number_of_sold_str = request.POST.get('number_of_sold')

        # Check if number_of_sold_str is not empty and contains only digits
        if number_of_sold_str and number_of_sold_str.isdigit():
            number_of_sold = int(number_of_sold_str)
            
        else:
            return JsonResponse({"error": "Invalid number_of_sold value. Must be a positive integer."}, safe=False, status=400)

        try:
            car = Cars.objects.get(id=car_id)
            car.sold(number_of_sold)
            return JsonResponse({"message": "Car sold successfully."}, safe=False)
        except Cars.DoesNotExist:
            return JsonResponse({"error": "Car not found."}, safe=False, status=404)
        except ValueError as ve:
            return JsonResponse({"error": str(ve)}, safe=False, status=400)

    return JsonResponse({"error": "Invalid request method."}, safe=False, status=400)




def update_transaction(request,transaction_id):
    transaction = get_object_or_404(Transaction, id=transaction_id)

    if request.method == 'POST':
        form = UpdateTransactionForm(request.POST, instance=transaction)
        if form.is_valid():
            form.save()
            return redirect('crm:transaction_list')
    else:
        form = UpdateTransactionForm(instance=transaction)

    return render(request, 'crm/sell/transaction_update_form.html', {'form': form, 'transaction': transaction})


@login_required
def delete_transaction(request, transaction_id):
    transaction = get_object_or_404(Transaction, id=transaction_id)
    if request.method == 'DELETE':
        transaction.delete()
        return JsonResponse({'message': 'Transaction deleted successfully'}, status=200)
    
    return JsonResponse({'error': 'Invalid request method'}, status=400)



# leas view
@login_required
def leasing_list(request):
    leases = Leasing.objects.all()
    context = {'leases': leases}
    return render(request, 'crm/lease/leasing_list.html', context)


@login_required
def add_lease(request):
    if request.method == 'POST':
        form = LeasingForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('crm:leasing_list')
    else:
        form = LeasingForm()

    return render(request, 'crm/lease/lease_a_car.html', {'lease_form': form})



@login_required
def lease(request):
    if request.method == 'POST':
        car_id = request.POST.get('id')
        number_of_lease_str = request.POST.get('number_of_lease')

        # Check if number_of_lease_str is not empty and contains only digits
        if number_of_lease_str and number_of_lease_str.isdigit():
            number_of_lease = int(number_of_lease_str)     
        else:
            return JsonResponse({"error": "Invalid number_of_lease value. Must be a positive integer."}, safe=False, status=400) 

        try:
            car = Cars.objects.get(id=car_id)
            car.lease(number_of_lease)
            return JsonResponse({"message": "Car leased successfully."}, safe=False)
        except Cars.DoesNotExist:
            return JsonResponse({"JSON error": "Car not found."}, safe=False, status=404)
        except ValueError as ve:
            return JsonResponse({"value error": str(ve)}, safe=False, status=400)

    return JsonResponse({"request error": "Invalid request method."}, safe=False, status=400)


def update_lease(request,lease_id):
    leasing = get_object_or_404(Leasing, id=lease_id)

    if request.method == 'POST':
        form = UpdateLeasingForm(request.POST, instance=leasing)
        if form.is_valid():
            form.save()
            return redirect('crm:leasing_list')
    else:
        form = UpdateLeasingForm(instance=leasing)

    return render(request, 'crm/lease/lease_update_from.html', {'form': form, 'leasing': leasing})


@login_required
def delete_lease(request, lease_id):
    lease = get_object_or_404(Leasing, id=lease_id)
    if request.method == 'DELETE':
        lease.delete()
        return JsonResponse({'message': 'Lease deleted successfully'}, status=200)
    
    return JsonResponse({'error': 'Invalid request method'}, status=400)

crm_project/crm/templates/crm/customer/add_customer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Customer</title>
</head>
<body>
    <h2>Add a new Customer</h2>
    <form method="post" action="{% url 'crm:add_customer' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Customer</button>
    </form>
    <a href="{% url 'crm:customer_details' %}" class="btn btn-secondary">Cancel</a>
</body>
</html>

crm_project/crm/templates/crm/customer/customer_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Customers</title>
</head>
<body>
    <h2>Customers Details</h2>
    <button type="button" class="btn btn-secondary" data-dismiss="modal">
        <a href="{% url 'crm:dashboard' %}" class="btn btn-primary">Back</a>
    </button>
    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#addRecordModal">
        <a href="{% url 'crm:add_customer' %}" class="btn btn-primary">Add Customer</a>
    </button>
    <table border="1">
        <thead>
            <tr>
                <th>User ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Phone Number</th>
                <th>Address</th>
                <th>Cars Bought</th>
                <th>Cars on Lease</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for customer in customers %}
                <tr>
                    <td>{{ customer.id }}</td>
                    <td>{{ customer.name }}</td>
                    <td>{{ customer.email }}</td>
                    <td>{{ customer.phone_number }}</td>
                    <td>{{ customer.address }}</td>
                    <td></td>
                    <td></td>
                    <td>
                        <a href="{% url 'crm:update_customer' user_id=customer.id %}">Update</a>
                        <a href="#" class="delete-customer-link" data-customer-id="{{ customer.id }}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        // Add event listener to all delete links
        document.querySelectorAll(".delete-customer-link").forEach(function (link) {
            link.addEventListener("click", function (event) {
                event.preventDefault();

                // Get car ID from the data attribute
                var customerId = this.getAttribute("data-customer-id");
                // Show a confirmation dialog
                var isConfirmed = confirm("Are you sure you want to delete this customer?");

                // If user confirms, send AJAX request to delete
                if (isConfirmed) {
                    deleteCustomer(customerId);
                }
            });
        });

        function deleteCustomer(customerId) {
            // Get CSRF token from cookies
            var csrfToken = getCookie('csrftoken');
            
            // Use fetch API to send AJAX request for delete
            fetch(`/crm/delete_customer/${customerId}/`, {
                method: 'DELETE',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrfToken,
                },
                body: JSON.stringify({}),  // Pass an empty JSON object as the body
            })
            .then(function (response) {
                if (response.ok) {
                    // Optionally, update the UI or show a success message
                    console.log("Customer deleted successfully");
                    // Reload the current page to refresh the table
                    window.location.reload();
                } else {
                    // Handle error
                    console.error("Failed to delete customer");
                }
            });
        }
        // Function to get CSRF token from cookies
        function getCookie(name) {
            var value = "; " + document.cookie;
            var parts = value.split("; " + name + "=");
            if (parts.length === 2) return parts.pop().split(";").shift();
        }
    });
</script>
</html>

crm_project/crm/templates/crm/customer/customer_update_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Customer</title>
</head>
<body>
    <h2>Update Customer</h2>
    <form method="post" action="{% url 'crm:update_customer' user_id=customer.id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update Car" class="btn btn-primary">
    </form>
    <a href="{% url 'crm:customer_details' %}" class="btn btn-secondary">Cancel</a>
</body>
</html>